"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateCheckoutSessionComposer = void 0;
const CreateCheckoutSessionController_1 = require("@interfaces/controller/Client/Sessions/CreateCheckoutSessionController");
const CreateChekoutSessionUseCase_1 = require("@src/application/usecases/Client/implementations/CreateChekoutSessionUseCase");
const UserRepo_1 = require("@infrastructure/database/repo/UserRepo");
const LawyerRepo_1 = require("@infrastructure/database/repo/LawyerRepo");
const AppointmentsRepo_1 = require("@infrastructure/database/repo/AppointmentsRepo");
const ScheduleSettingsRepo_1 = require("@infrastructure/database/repo/ScheduleSettingsRepo");
const AvailableSlotsRepo_1 = require("@infrastructure/database/repo/AvailableSlotsRepo");
const OverrideSlotsRepo_1 = require("@infrastructure/database/repo/OverrideSlotsRepo");
const WalletRepo_1 = require("@infrastructure/database/repo/WalletRepo");
const LawyerVerificationRepo_1 = require("@infrastructure/database/repo/LawyerVerificationRepo");
const LawyerVerificaitionMapper_1 = require("@infrastructure/Mapper/Implementations/LawyerVerificaitionMapper");
const RedisService_1 = require("@infrastructure/Redis/RedisService");
const RedisConfig_1 = require("@infrastructure/Redis/Config/RedisConfig");
const HttpErrors_1 = require("@interfaces/helpers/implementation/HttpErrors");
const HttpSuccess_1 = require("@interfaces/helpers/implementation/HttpSuccess");
const CommissionSettingsRepo_1 = require("@infrastructure/database/repo/CommissionSettingsRepo");
const CommissionSettingsMapper_1 = require("@infrastructure/Mapper/Implementations/CommissionSettingsMapper");
const UserSubscriptionRepository_1 = require("@infrastructure/database/repo/UserSubscriptionRepository");
const UserSubscriptionMapper_1 = require("@infrastructure/Mapper/Implementations/UserSubscriptionMapper");
const CreateCheckoutSessionComposer = async () => {
    const client = await (0, RedisConfig_1.connectRedis)();
    const useCase = new CreateChekoutSessionUseCase_1.CreateCheckoutSessionUseCase(new UserRepo_1.UserRepository(), new LawyerVerificationRepo_1.LawyerVerificationRepo(new LawyerVerificaitionMapper_1.LawyerVerificationMapper()), new AppointmentsRepo_1.AppointmentsRepository(), new ScheduleSettingsRepo_1.ScheduleSettingsRepository(), new AvailableSlotsRepo_1.AvailableSlotRepository(), new OverrideSlotsRepo_1.OverrideSlotsRepository(), new WalletRepo_1.WalletRepo(), new LawyerRepo_1.LawyerRepository(), new RedisService_1.RedisService(client), new CommissionSettingsRepo_1.CommissionSettingsRepo(new CommissionSettingsMapper_1.CommissionSettingsMapper()), new UserSubscriptionRepository_1.UserSubscriptionRepository(new UserSubscriptionMapper_1.UserSubscriptionMapper()));
    return new CreateCheckoutSessionController_1.CreateCheckoutSessionController(useCase, new HttpErrors_1.HttpErrors(), new HttpSuccess_1.HttpSuccess());
};
exports.CreateCheckoutSessionComposer = CreateCheckoutSessionComposer;
